/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
          "on-tertiary-fixed-variant": "#454747",
          "surface-variant":           "#f1f1f1",
          "surface-container-high":    "#f1f1f1",
          "surface-tint":              "#FF4D00",
          "on-secondary":              "#ffffff",
          "background":                "#f8f9fa",
          "tertiary-fixed-dim":        "#c6c6c7",
          "secondary-fixed-dim":       "#c6c6c6",
          "on-primary-fixed-variant":  "#852400",
          "surface-dim":               "#f1f1f1",
          "primary":                   "#FF4D00",
          "surface-container-lowest":  "#ffffff",
          "surface-container-low":     "#ffffff",
          "outline":                   "#e2e2e2",
          "outline-variant":           "#f1f1f1",
          "surface-container-highest": "#e2e2e2",
          "inverse-surface":           "#1b1c1c",
          "tertiary-fixed":            "#e2e2e2",
          "primary-fixed-dim":         "#ffb59e",
          "on-error":                  "#ffffff",
          "secondary-fixed":           "#e2e2e2",
          "inverse-primary":           "#ffb59e",
          "on-secondary-fixed-variant":"#474747",
          "primary-fixed":             "#ffdbd0",
          "on-primary":                "#ffffff",
          "surface-bright":            "#ffffff",
          "on-tertiary-fixed":         "#1a1c1c",
          "on-surface-variant":        "#5e5e5e",
          "secondary-container":       "#f1f1f1",
          "on-primary-fixed":          "#3a0b00",
          "on-secondary-container":    "#646464",
          "secondary":                 "#5e5e5e",
          "on-tertiary-container":     "#fcfcfc",
          "error":                     "#ba1a1a",
          "tertiary":                  "#5b5c5c",
          "surface-container":         "#f1f1f1",
          "surface":                   "#f8f9fa",
          "on-error-container":        "#93000a",
          "on-primary-container":      "#ffffff",
          "inverse-on-surface":        "#f2f0f0",
          "primary-container":         "#FF4D00",
          "on-surface":                "#1b1c1c",
          "on-background":             "#1b1c1c",
          "background-light":          "#ffffff",
      },
      spacing: {
          "xl": "80px",
          "md": "24px",
          "gutter": "24px",
          "base": "8px",
          "container-max": "1440px",
          "margin-mobile": "16px",
          "xs": "4px",
          "sm": "12px",
          "margin-desktop": "64px",
          "lg": "48px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        "headline-lg-mobile": ["Manrope"],
        "label-sm": ["Inter"],
        "headline-md": ["Manrope"],
        "label-bold": ["Inter"],
        "display-xl-mobile": ["Manrope"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "display-xl": ["Manrope"]
      },
      fontSize: {
          "headline-lg-mobile": ["32px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500"}],
          "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "label-bold": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
          "display-xl-mobile": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "800"}],
          "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
          "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "display-xl": ["80px", {"lineHeight": "88px", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
